server: 
  port: 9001
eureka: 
  instance: 
    hostname: discovery2
    appname: DiscoveryServer
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: http://discovery1:9000/eureka/