## 打印更细致的sql语句，等价于将mybatis日志级别设置为trace
#mybatis:
#    configuration:
#         log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# redis
spring:
  redis:
    # redis的连接ip
    host: 52.81.95.160
    # redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    # 连接超时时间（毫秒)
    timeout: 10000ms
    #  springboot2.0后默认使用lettuce连接redis,底层使用的是netty框架做支撑
    lettuce:
      pool:
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8